version: '3.2'

services:
#  tester:
#    build: .
#    links:
#      - kafka
#      - zookeeper
#      - suricata
#    volumes:
#      - .:/mount
#      - .:/pcaps
#    command: cargo test

#  suricata:
#    build: docker/suricata
#    volumes:
#      - .:/pcaps

  kafka:
    build: docker/kafka
    logging:
      driver: none  # Hide output
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    links:
      - zookeeper

  zookeeper:
    build: docker/zookeeper
    logging:
      driver: none  # Hide output
    expose:
      - "2181"
